### ISSUE TITLE
Include weakly labeled elements when exporting labeled data

### ISSUE THREAD

**Issue by alonh** [label-sleuth/label-sleuth#174]
**Is your feature request related to a problem?**
When exporting labeled data, weak labels that were used for training are not included in the file.

**What is the expected behavior?**
Include weak labels when exporting labeled data. Mark them so the user can decide whether to use them or not.

**Additional context (if any):**

**Comment by martinscooper** [comment]
Weak labels are already available to be download on the system's UI. Closing this issue.
