### ISSUE TITLE
How can I use the trained model to evaluate new datasets?

### ISSUE THREAD

**Issue by cgnerds** [label-sleuth/label-sleuth#182]
Your work is great, and thank you very much! 
By the way , can you kindly tell me how to use the trained model to evaluate new dataset file (like a csv file) ? This will be more userful to see the predicted result.
Thanks!

**Comment by arielge** [comment]
Hi,
You can upload an additional csv file to an existing dataset, effectively adding new documents to the dataset. If you do this, the system will perform inference on these new documents you uploaded using the latest trained model.
The inference happens in the background when you upload the new csv, although the system does not currently reflect this process to the user (this is a work in progress). Hence, we recommend to wait a couple minutes before opening the workspace to see the predictions.
Please let us know if this is what you were looking for.

**Comment by cgnerds** [comment]
> 

Thank you for your reply. This can partialy solve my problem. But I want to know if I can use the trained model without the front end? Like https://huggingface.co/yiyanghkust/finbert-tone.

**Comment by arielge** [comment]
@cgnerds While we do not directly support this at the moment, the following script should work:

```python
import os
from pathlib import Path

from label_sleuth.models.core.catalog import ModelsCatalog
from label_sleuth.models.core.models_background_jobs_manager import ModelsBackgroundJobsManager
from label_sleuth.models.core.models_factory import ModelFactory
from label_sleuth.models.core.tools import SentenceEmbeddingService
from label_sleuth.orchestrator.core.state_api.orchestrator_state_api import OrchestratorStateApi, IterationStatus

workspace_id = <YOUR_WORKSPACE_ID>
category_name = <YOUR_CATEGORY_NAME>
my_texts = ['text to infer 1', 'text to infer 2']

output_dir = os.path.join(str(Path.home()), 'label-sleuth')
model_type = ModelsCatalog.SVM_ENSEMBLE

state_api = OrchestratorStateApi(os.path.join(output_dir, "workspaces"))
model_factory = ModelFactory(output_dir=os.path.join(output_dir, 'models'),
                             models_background_jobs_manager=ModelsBackgroundJobsManager(),
                             sentence_embedding_service=SentenceEmbeddingService(output_dir))

category_id = [cat_id for cat_id, cat in state_api.get_all_categories(workspace_id).items()
               if cat.name == category_name][0]
model_id = state_api.get_all_iterations_by_status(workspace_id=workspace_id, category_id=category_id,
                                                  status=IterationStatus.READY)[-1][0].model.model_id
model = model_factory.get_model(model_type)

results = model.infer(model_id, [{'text': t} for t in my_texts])
print(results)
```

Note that if you specified a custom path for the output directory or used a different model type than the default one or you need to change the value of the `output_dir` and/or `model_type` variables.

**Comment by cgnerds** [comment]
Thank you very much!
