### ISSUE TITLE
Pagination in right panel element lists

### ISSUE THREAD

**Issue by arielge** [label-sleuth/label-sleuth#194]
**Is your feature request related to a problem?**
Currently the element lists on the right panel are static and with a predefined size. This means the user cannot view more than X results, and/or must scroll through a very long list.

**What is the expected behavior?**
Pagination

**Additional context (if any):**
Some of the relevant endpoints in the backend already support pagination, but this is not reflected in the frontend.

**Comment by martinscooper** [comment]
@arielge could you specify which backend endpoints already support pagination?

**Comment by arielge** [comment]
Endpoints currently supporting pagination:

- `query ("/workspace/<workspace_id>/query")` [Search panel]
- `get_elements_to_label ("/workspace/<workspace_id>/active_learning")` [Label next panel]
- `get_positive_predictions ("/workspace/<workspace_id>/positive_predictions")` [Positive predictions panel]
- `get_document_positive_predictions ("/workspace/<workspace_id>/document/<document_uri>/positive_predictions")`
