### ISSUE TITLE
Improve the visibility of the Webpage link

### ISSUE THREAD

**Issue by martinscooper** [label-sleuth/label-sleuth#206]
**Is your feature request related to a problem?**

The Webpage link at the botom left of workspace page is difficult to read in some screens.

![image](https://user-images.githubusercontent.com/22247838/187468714-bb37c0c8-35cc-4550-9c9c-149a8902635c.png)

**What is the expected behavior?**
It should be easy to read and to notice. Increasing the font weight should solve the issue.

**Comment by Kelp710** [comment]
HI! I`d like to tackle this issue.

**Comment by martinscooper** [comment]
I went ahead and worked on this issue, as the PR that solves it has been stale for two months
