### ISSUE TITLE
[Frontend] tabValue and tabStatus manage the same logic

### ISSUE THREAD

**Issue by martinscooper** [label-sleuth/label-sleuth#207]
**Is your feature request related to a problem?**

The [WorkspaceInfo component](https://github.com/label-sleuth/label-sleuth/blob/ceb83e6989b70df65f704bba411177e48819cac2/frontend/src/modules/Workplace/information/WorkspaceInfo.jsx#L128) has two variables created using `React.useState()` that manage the state of the tab panel, `tabValue` and `tabStatus`. `tabStatus` is not being used. 

![image](https://user-images.githubusercontent.com/22247838/187473880-b03260a3-ae57-49ee-be80-3154cffd23f6.png)

**What is the expected behavior?**
Remove the `tabStatus` state and all the usages if `setTabStatus()`.

**Comment by chaitanya-24** [comment]
Can I work on this issue?

**Comment by martinscooper** [comment]
Hi @chaitanya-24. Please, go ahead!

**Comment by Kelp710** [comment]
Hi! Can I contribute to this issue?
And when I run the workplace page on localhost, Any changes to the React files don`t appear on the page. But changes on the compiled version of the frontend under label_sleuth/build do. Could someone tell me how I can make changes with jsx files? 
Thank you.

**Comment by martinscooper** [comment]
Hi @Kelp710 yes, you can take this issue. 

Regarding the changes in the React app's sourcecode not being applied, you can follow the steps described in the [frontend folder](https://github.com/label-sleuth/label-sleuth/tree/main/frontend). Running `npm run start` will start a server at `localhost:3000` that is reloaded anytime a file change is detected. At the same time, the backend is statically serving the compiled frontend code located in `/label_sleuth/build` in `localhost:8000`. For local development, you should use  `localhost:3000`.

**Comment by Kelp710** [comment]
Thank you so much!!
