### ISSUE TITLE
Model predictions in the "Positive labels" panel do not update

### ISSUE THREAD

**Issue by arielge** [label-sleuth/label-sleuth#211]
**What is the current behavior?**
After a new model is ready, the blue frames around the elements in the "Positive labels" panel still reflect the predictions of the previous model. After reopening the category / refreshing the page the correct predictions are shown.

**What is the expected behavior?**
The positive labels panel contents should be updated whenever a new model is ready.

**Comment by martinscooper** [comment]
@arielge I will add this bug fix to the `refactor` branch. The action that gets all the positive labels when the category or model version changes was not being dispatched.

**Comment by arielge** [comment]
resolved by #200
