### ISSUE TITLE
Frontend issues with parentheses in the search bar

### ISSUE THREAD

**Issue by arielge** [label-sleuth/label-sleuth#212]
**What is the current behavior?**
Typing in parentheses or brackets in the search bar can cause a blank page to appear.

**Steps to reproduce the problem:**
1. Search using the search bar, for any expression that returns some results in the dataset.
2. After the results have returned, modify the contents of the search bar, and type in any one of the following characters: `][)(`

**Environment:**
 - OS: macOS
 - Web browser: Chrome / Safari

**Comment by martinscooper** [comment]
After disabling regular expressions by default, this issue doesn't exist anymore. However, a different issue should be created to propose a solution to add the functionality to let the user specify that the search input in the search bar is a regular expression.

@yannisk2 @shnarch do you think that we still want to support regular expressions? If so, we could add an icon/checkbox near the search bar.

<img width="378" alt="image" src="https://user-images.githubusercontent.com/22247838/204380370-2035768d-0334-4584-b05c-7c700a0ec551.png">

We could potencially follow Visual Studio Code IDE's approach. See following image.

<img width="492" alt="image" src="https://user-images.githubusercontent.com/22247838/204380600-a2b7dcb5-0f43-4eb2-8073-0ab6024f4540.png">

**Comment by arielge** [comment]
@martinscooper As far as I can tell the frontend issue is still there. It is not an issue with regular expressions but with the use of parentheses in search (and is most likely related to the highlighting of search results)

**Comment by shnarch** [comment]
regarding bringing back regular expressions - I'm in favor! I really needed today the ability to type a more complicated search query: e.g., NUMBER + specific_word, or word1 [any size of text in between] word2.
I was thinking about adding a checkbox near the search box to enable regular expressions (like in Notepad++ or similar text editors). I also like the Visual Studio Code IDE's approach @martinscooper proposed. Do you think it is harder to understand than a single checkbox?

**Comment by yannisk2** [comment]
Getting back to this issue to see how this can be fixed. I agree with @arielge that it seems related to the highlighting of results. In particular, based on preliminary testing, it seems to get resolved if at https://github.com/label-sleuth/label-sleuth/blob/598e26a5f7851aad38b692955d30bde512390c57/frontend/src/modules/Workplace/sidebar/Element.jsx#L116 we switch the value of `autoEscape` to true.

@martinscooper could you please take a deeper look when you get a chance?

**Comment by martinscooper** [comment]
@yannisk2 Thanks for your suggestion. Indeed, setting `autoEscape` to `true` solves the issue. 

We will have to change its dinamically once we let the user activate the regex search in the future.

I will merge the change and close the issue in a moment.
