### ISSUE TITLE
[backend] Add a flag for the search endpoint to enable/disable regex search

### ISSUE THREAD

**Issue by alonh** [label-sleuth/label-sleuth#219]
**Is your feature request related to a problem?**
Currently, the search endpoint uses regex by default which might be confusing for some users.

**What is the expected behavior?**
The search endpoint will not use regex by default. A flag will be passed to the endpoint to turn the regex search on.

**Additional context (if any):**
Later, the frontend could add a checkbox to enable/disable regex search

**Comment by martinscooper** [comment]
This issue has been already resolved. Closing it.
