### ISSUE TITLE
Training model does not get created due to FileNotFoundError

### ISSUE THREAD

**Issue by nshahani** [label-sleuth/label-sleuth#237]
**What is the current behavior?**
The Training Model does not get created. The UI keeps displaying the message Training in progress inspite of waiting for several hours. Ultimately, the Current Model shows as "Not Available yet"
<img width="393" alt="image" src="https://user-images.githubusercontent.com/36721205/191344979-000aaf94-4143-49b2-9432-832e733db879.png">

**What is the expected behavior?**
Training should completed in few minutes at the most, and the model should be available. If there is an issue with creating the training model, user should be notified that there was a problem and that the training model could not be created, along with guidance on what to do next/how to get help(eg. create an issue in this github repo)

**Steps to reproduce the problem:**
1. Set Home/default directory to a longish name Or install label-sleuth in a directory with a long name -  "eg C:\Users\SheshadriChandrashek"
2. Follow the installation steps as documented on label-sleuth getting started guide, install on Windows OS
3. Upload data, begin labeling until 100%, wait for training model to be created.

**Environment:**
 - OS: Windows
 - Web browser: Chrome
 - Python version: 3.8

**Suggested solution (if any):**

**Comment by martinscooper** [comment]
Hi @nshahani, thanks for reporting this issue! We have reduced the model path length so this error doesn't happens anymore. We are currently working on improving the model creation error notifications so the user is aware what something went wrong.

**Comment by nshahani** [comment]
great, thanks very much @martinscooper

**Comment by martinscooper** [comment]
The model creation error notifications are already in the last Pypi version. A notification will show up giving an explanation to the user on how to proceed. Closing this issue.
