### ISSUE TITLE
Import List of Classes/Labels when starting out

### ISSUE THREAD

**Issue by strwberry-smggls** [label-sleuth/label-sleuth#262]
**Is your feature request related to a problem?**
I'm trying to import a dataset that already has a set number of 10 classes. However, I need to create each class manually instead of being able to import a list of classes quickly. This can become a problem, especially if there are even more classes and/or more datasets.

**What is the expected behavior?**
I would like to be able to import a list of class names instead of typing in each class name individually by hand.

**Comment by strwberry-smggls** [comment]
My goal was indeed to start with a training set that has either no labels or not all labels are represented. As such, the functionality of importing labels in a file is what I am looking for. I can contribute the improvement with a little time reading into the code.

**Comment by alonh** [comment]
Great to see it meets your requirements. 
We will be happy to get your contribution.

Closing this issue.
