### ISSUE TITLE
Expose shortcuts so users are aware of them

### ISSUE THREAD

**Issue by martinscooper** [label-sleuth/label-sleuth#276]
**Is your feature request related to a problem?**

As part of the issue #253, shortcuts has been added to perform actions on the sidebar panel. Currently, we don't expose the information about which shortcuts are available anywhere. This means we are on an incosistent state: because of shortcuts, a sidebar element is focused by default (i.e. has a yellow background) and the user has no clue of why it has that style. 

Based on a discussion with @yannisk2, we came up to four different options we could implement in order to let users know about the available shortcuts. Those are:

- Tooltips: when a user hovers a button that has a shortcut associated, show a tooltip with the action and the shortcut key. For example: positive and negative labeling buttons. Not all shortcuts actions have a button associated (i.g. going to the next or previous element).

Example from Microsoft Word:
 
![image](https://user-images.githubusercontent.com/22247838/200580709-6df41c2a-00b0-4b4f-a46d-901a94bfac77.png)

- Modal: display a modal that lists all the available shortcuts and explain them. 

Jupyter follows this approach: 
![image](https://user-images.githubusercontent.com/22247838/200578487-63720e45-f7d2-4c7b-bbed-f62bb714ce30.png)

- Notifications: we could display notifications with a message that reminds the user that there are shortcuts available for the action they are performing. Example: user clicks an element to discover its document on the main view -> a message informing that pressing enter would do the trick if the element is focused or something like "You can go to ? to see the available shortcuts" where pressing ? opens the modal described in the previous item.

- Tutorial: expose the shortcuts on the tutorial. This could be done a) when showing the user how to use the sidebar panels or b) having a whole tutorial step dedicated to shortcuts.

**Comment by alonh** [comment]
all options seem good to me. 
How will you notify the user about shortcuts that are not directly related to an icon in the tooltip option?
I'm in favor of combining the second (the list) with the 4th (mentioning this in the tutorial)

**Comment by shnarch** [comment]
how about showing (on the screen) a very short keyboard shortcuts which are relevant for the task the user is currently doing?

**Comment by martinscooper** [comment]
After an internal discussion, we will use the following approach for exposing the shortcuts:

- Use tooltips for positive and negative labeling.
- Create a modal that lists all the available shortcuts and that is opened with the `Shift + ?` shortcut. 
- When first model is ready, open a toast notification that inform the user about the shortcut for opening the modal. This modal has to be opened only once.
