### ISSUE TITLE
Possible bug regarding predictions when using BERT model

### ISSUE THREAD

**Issue by stefanoscotta** [label-sleuth/label-sleuth#286]
I experience the following bug, it seems quite strange to me, but if anyone could verify as well it would be nice. 

**What is the current behavior?**
Using the model implemented in [hf_tranformers.py ](https://github.com/label-sleuth/label-sleuth/blob/c2105d9183c1f661f22ee72d91921afbda4afa6e/label_sleuth/models/hf_transformers.py) I experience that the scores returned in the predictions are all >0.5. Hence, all the sencences of the database result labelled as "True". I think it is due to the fact that the pipeline used to interpret the results of the BERT model returns the inferences as {'label': LABEL_x, 'score': d}, where d will always be >0.5, because it is the reason for which the label is x and not y.
![image](https://user-images.githubusercontent.com/113582017/201884758-b8f9f375-3470-483c-ad71-98231c759a0d.png)

**What is the expected behavior?**
It should assign to each elements a score corresponding to the "probability" of that sentence to be True, not the probability to be the LABEL assigned by the model. 

**Steps to reproduce the problem:**

1. Perform a training setting the [model policy](https://github.com/label-sleuth/label-sleuth/blob/c2105d9183c1f661f22ee72d91921afbda4afa6e/label_sleuth/config.json#L6) as "STATIC_HF_BERT".
2. Then you will see that all the sentences are labelled as positive.

**Environment:**
 - Web browser: Chrome
 - Python version: 3.9

**Suggested solution (if any):**
I experimented that to solve this bug it is enough to replace the [line ](https://github.com/label-sleuth/label-sleuth/blob/c2105d9183c1f661f22ee72d91921afbda4afa6e/label_sleuth/models/hf_transformers.py#L90) with something like:
```       
        scores=[]
        for p in preds:
            if p['label']=='LABEL_0':
                scores.append(1-p['score'])
            if p['label']=='LABEL_1':
                scores.append(p['score'])
```

**Comment by arielge** [comment]
@stefanoscotta Thanks for the catch! fixing
