### ISSUE TITLE
Uploading labels fails when the csv header has spaces

### ISSUE THREAD

**Issue by martinscooper** [label-sleuth/label-sleuth#315]
There is a 500 error when uploading labels where the csv header has spaces. For example, uploading a csv file with the following header fails:

`text,category_name, label`

Note the space between `,` and `label`.

**Comment by martinscooper** [comment]
I took a look at what's happening. When converting the csv file to a DataFrame, the column names are not trimmed and thus named with the whitespace on them. Because of that a KeyError is raised when looking for the `DisplayFields` on the DataFrame. 

Adding `.rename(columns=lambda x: x.strip())` to [this line](https://github.com/label-sleuth/label-sleuth/blob/629097fafe67e079fb77883b92da8f91304cf141/label_sleuth/app.py#L719) solves the issue.

**Comment by martinscooper** [comment]
@arielge @alonh what's your opinion of this issue?

**Comment by alonh** [comment]
looks like a good solution to the problem. Can you apply this change?

**Comment by martinscooper** [comment]
The same issue can be observed when adding documents. I will addressed both.
