### ISSUE TITLE
Improve label import runtime

### ISSUE THREAD

**Issue by alonh** [label-sleuth/label-sleuth#319]
**Is your feature request related to a problem?**
when loading 1000+ labeled elements for multiple categories, the import process can take a few minutes.

**What is the expected behavior?**
much faster labels import.

**Additional context (if any):**
one possible reason for this might be that in some datasets there are many duplicate sentences and the process of finding these duplications when applying the labels takes time. This could be a good place to start debugging.

**Comment by martinscooper** [comment]
This issue has been addressed on PR https://github.com/label-sleuth/label-sleuth/pull/351. Refer to the PR's description to find out mroe details about the performance improvement numbers.
