### ISSUE TITLE
Wrong field name specified in documentation

### ISSUE THREAD

**Issue by yoavkatz** [label-sleuth/label-sleuth#348]
**What is the current behavior?**

Text in documentation of API is:

The uploaded csv file must adhere to the following format: It should include a ‘text’ column, and may optionally include a ‘doc_id’ column as well as metadata columns starting with the ‘metadata_’ prefix.

**What is the expected behavior?**

Should be 'document_id'

**Comment by alonh** [comment]
Thanks for pointing this out.
fixed in commit [b1b6c8623a60c0a59fbe2a98557b3aa6a90a3bcc](https://github.com/label-sleuth/label-sleuth.org/commit/b1b6c8623a60c0a59fbe2a98557b3aa6a90a3bcc)
