### ISSUE TITLE
'Label element for non-current category' design and implementation

### ISSUE THREAD

**Issue by martinscooper** [label-sleuth/label-sleuth#356]
This issue has the intention of discussing the 'label for non-current category' functionality UI design. 'label for non-current category' means labeling an element for a category that is different from the one that is currently selected. This shouldn't require any changes on the backend side.

### Design ideas
- A 3 dots menu will me shown on the upper-right corner of each document element. This button will me displayed only if the element is focused (i.e. the click is over that element). 
- Clicking the 3 dots button will open a menu with options. First one is the 'Label for another category'. Another one could be 'See all predictions' or similar for when the multi label functionality is there.
- Clicking on 'Label for another category' will open a list of the other categories on the same menu tree. Here we have to decide whether we let the user to label the element as positive or negative or only as negative.
  - Positive or negative labeling: on this option we could include another menu tree level, where clicking on the element opens the options to label as positive or negative, maybe just using the V or X icon buttons.
   - Only positive labeling: on this option we should make sure that the user understands that they will be labeling the element as positive. Maybe naming this menu option as 'Label as positive for another category' could be an option.

### Observations/Doubts:
- The menu button would be active only if there are more categories than the one that is currently selected.
- The element that the user wants to label for another category could have been already labeled by the user. Thus, labeling it could remove the previous label if the user don't remember they already labeled it. We should add an indicator of whether an element is already labeled. An option is to make the color of the category name red or green as we do with the elements if the element is labeled for that category.
- As the number of categories can be large for some use cases, we have to think of how to deal with this, because the list of categories could overflow the screen and make finding a category name difficult. Options to deal with this are: 
  - Make this list to be scrollable or some similar mechanism.
  - Add a query input to filter the list of categories.

**Comment by alonh** [comment]
> The element that the user wants to label for another category could have been already labeled by the user. Thus, labeling it could remove the previous label if the user don't remember they already labeled it. We should add an indicator of whether an element is already labeled. An option is to make the color of the category name red or green as we do with the elements if the element is labeled for that category.

This is a good point. When retrieving an element, the backend exposes the labels for all categories, so it is possible to communicate that information label to the user. I think we should stick to the like and dislike icons to avoid confusion.

> Clicking on 'Label for another category' will open a list of the other categories on the same menu tree. Here we have to decide whether we let the user to label the element as positive or negative or only as negative.

We aim to find positive elements, as in most cases it will help the model the most. But there are probably scenarios where the user will want to label as negative to a different category, so my opinion is that we should allow both. (and preserve the look and feel of the regular labeling).

**Comment by yannisk2** [comment]
@martinscooper @alonh thanks for starting the discussion on this! I just wanted to add two ideas/thoughts:

- _Reducing number of steps required for assigning an element to another category:_ To make the process of assigning an element to a different category as fast as possible, could we instead of having 3 step process (i.e., 3 dots icon - menu of element options - menu of available categories), remove one step by creating an icon at the element level that brings up the menu of available categories directly? The potential drawback is that if we want to introduce more element options in the future, we run the risk of overcrowding the UI. However, given that we do not have other such element options for now (and we do not yet know whether overcrowding will ever become an issue), I was wondering whether we can avoid the additional level of indirection for now. What do you think?
 
- _Keyboard shortcuts:_ Now that we have such an efficient way of labeling using the keyboard shortcuts, could we create the design also with keyboard support in mind (even if we stage the implementation to add keyboard support later on)?

**Comment by martinscooper** [comment]
Thanks @yannisk2 and @alonh  for your comments.
- I agree with Yannis regarding removing a level of indirection, like a button next to the V and X buttons. We should decide which button would feat. Intuitively I think of a + button, with an appropiate tooltip.
- Adding shortcuts for this features sounds good. Let's not plan it for a first stage but I definitly agree on adding them next.
- I agree with Alon, let the user label both as positive and negative. We don't know yet which scenarios would require to make a negative label for another category, but I mainly like this option because it preserves the look and feel of the regular labeling.

I can already start implementing this. cc: @alonh @yannisk2 @arielge.

**Comment by martinscooper** [comment]
https://labelsleuth.slack.com/archives/C044SSUAHNF/p1677275132249179
