### ISSUE TITLE
"Label next" and "Positive predictions" panels revert to 1st page of results

### ISSUE THREAD

**Issue by yannisk2** [label-sleuth/label-sleuth#388]
**What is the current behavior?**
In the "Label next" and "Positive predictions" panels, when I switch from the 1st page of results to some other page, Label Sleuth switches to the selected page but after a few seconds it reverts by itself back to the 1st page.

**What is the expected behavior?**
When another page is selected in one of the affected panels, the system should switch to and remain on the selected page. 

**Steps to reproduce the problem:**

These are the steps to reproduce the problem for the "Label next" panel:
1. Select workspace and category that already has a trained model (so that the affected panels can appear). Since the problem often disappears after interacting with the panel a few times, make sure right before trying to reproduce the issue to go back to the main page and then enter a workspace and/or refresh the page (if you are already inside a workspace). 
2. Go to the "Label next" panel (if it is not already shown)
3. Click on a page indicator other than 1 at the bottom of the panel to switch to another page of results. The system should show the selected page.
4. Wait a few seconds (note: it is not immediate). The system will revert back to the 1st page. 

The problem for the "Positive predictions" panel can be reproduced in a similar way. Make sure to refresh the page before trying to reproduce it, as sometimes if you already reproduced the issue on the "Label next" panel, the issue may not appear on the "Positive predictions" panel.

**Environment:**
 - OS: MacOS 12.6
 - Web browser: Safari or Chrome (I was able to reproduce the issue on both)
 - Python version: 3.8.13
 - Label Sleuth version (as it appears on the bottom left of the UI): v0.9.0-15-g94f5efa

**Comment by martinscooper** [comment]
I found the cause of the bug. The redux reducer that checks the status of the model version also resets the pagination of some of the panels in order to make them to be updated. The pagination is reseted even if there is no new model available. The bug fix consist on reseting the pagination only if there is a new model available, in which case we have to trigger the fetching of the elements.
