### ISSUE TITLE
text samples ids preservation

### ISSUE THREAD

**Issue by venturamor** [label-sleuth/label-sleuth#408]
Hi, 

Is there a possibility to download the labels CSV with the original ids of the text samples?
It is hard to find the samples in the order they were inserted in the original input.

thanks

**Comment by arielge** [comment]
Hi @venturamor,
So if I am understanding you correctly, this order information is reflected in the `uri` column of the labels csv. That is, this column has the system-generated ids for each sample, where the numbering within the id matches the order of the elements in the csv of documents that was uploaded into the system.
In addition, you also have the possibility to define *your own* ids when uploading the documents, and to have these saved along with the labels. The way to this is to include additional metadata columns in the csvs of documents you upload, marked by the `metadata_` prefix. So for example if you include a `metadata_id` column when uploading your dataset, then when you download a labels csv from a workspace that uses this dataset then this information will appear in the csv under an `element_metadata` column.

**Comment by arielge** [comment]
Note that in the latest version the metadata fields are exported in separate columns (matching the column names at dataset upload) rather than a single `element_metadata` column.
@venturamor Feel free to comment/reopen if this does not resolve your use case.
