### ISSUE TITLE
Clean up document names on the UI by removing dataset prefix

### ISSUE THREAD

**Issue by yannisk2** [label-sleuth/label-sleuth#440]
**Is your feature request related to a problem?**
Currently, document names on the UI are prefixed with the name of the dataset (e.g., `wiki_animals_2000_pages-Acanthobrama telavivensis`, where `wiki_animals_200_pages` is the dataset name and `Acanthobrama telavivensis` is the actual document name). I think that this makes the document names harder to read, as (a) they become long and (b) one has to always read and ignore the dataset name before getting to the actual name of the document.

**What is the expected behavior?**
To make document names easier to read, I think that it would help to remove the dataset name prefix from them. If we want to still display the dataset name on the UI, in a discussion I had with @martinscooper, he suggested displaying the dataset name on the left panel under the workspace name. Since the dataset is a property of a workspace, I agree that seems to be the natural location for it. 

What do you think?

**Comment by alonh** [comment]
I agree. Sounds like we should do these two changes together (remove from the document id and move to the left panel)
