### ISSUE TITLE
Indicate that an element has been labeled for other categories

### ISSUE THREAD

**Issue by yannisk2** [label-sleuth/label-sleuth#471]
**Is your feature request related to a problem?**
When the user is labeling elements for a category, it would help if they could see at a glance:
- if the element has already been labeled for other categories and
- which other categories it has been labeled for.

In order to accomplish that, users currently have to open the "+" menu and scroll through the list of categories to check for labels. This is a slow process that can disrupt the flow of labeling for the current category.

**What is the expected behavior?**
It would help if we made it easier for users to accomplish the above. We probably need a deeper design discussion for this, but here are some ideas that have been floated around and which may help in this discussion:
- Add indicator on the "+" icon similar to the notification indicators shown for apps. This can indicate that other labels exist for an element and even potentially show the number of such labels. Note that this would make the user aware at a glance of the existence of other labels, which is an improvement over the current design. However, it would not fully solve the problem of quickly discovering which are these labels (as the user would have to open the list and more importantly scroll through it). For this, we may  need additional improvements on the category list itself.

- Show labeled categories directly on the element itself (e.g., on the bottom left). This makes the information instantly visible on the UI. On the other hand, it risks overcrowding the UI. Moreover, this should be designed so that the view works both for elements shown on the side panels and elements shown on the document view and it should also scale if an element is assigned to a large number of categories.

**Comment by martinscooper** [comment]
An important point to make regarding your first suggestion is that the '+' button is shown only when the user hovers the element. Thus the user will only see the amount of categories that have been labeled unless they hover the element. I am assuming that we are willing to add this type of indicator because we want to quickly see which elements have been labeled to other categories. Based on this, this suggestion won't fill our need.

**Comment by martinscooper** [comment]
This is how it looks using the Badge component that MUI provides

Uploading Screen Recording 2023-04-04 at 17.42.11.mov…

**Comment by yannisk2** [comment]
Thanks @martinscooper for adding this in! I think it could work, but it currently feels that is is overpowering the rest of the buttons on the UI. I am wondering whether the following changes would help tie it better with the rest of the design:
- Move badge to the left of the '+' icon
- Change badge color to the color of the '+' icon
- Experiment with a slightly smaller badge size (if possible)

**Comment by martinscooper** [comment]
Good suggestions @yannisk2 ! I've applied all of them and:
- append the following text to the tooltip `(x already labeled)`.
- The tooltip is synchronize with the labeling actions.


https://user-images.githubusercontent.com/22247838/230122967-b2b48cd5-9451-4399-900d-ac933c331c6f.mov

**Comment by yannisk2** [comment]
Thanks a lot @martinscooper! This looks much nicer to me. @shnarch  @alonh @arielge what do you think about the latest design that @martinscooper implemented above?

**Comment by arielge** [comment]
Looks good!

**Comment by shnarch** [comment]
@martinscooper this looks good. @yannisk2 all your comments were very good.
@martinscooper just to make sure - in the second video, the plus sign of the second element does not present a badge because it was not labeled to any other category and not because the mouse did not hover over it (or something else that is needed to pop the badge)?

**Comment by martinscooper** [comment]
@shnarch no badge displayed means that that element hasn't been labeled to other category. We have these badge and tooltip on the plus sign of elements on the lists of the right panel too.

**Comment by martinscooper** [comment]
I will proceed to merge this new feature.
