### ISSUE TITLE
Precision evaluation is enabled when there are no positive predictions

### ISSUE THREAD

**Issue by alonh** [label-sleuth/label-sleuth#515]
**What is the current behavior?**
The user can open the precision evaluation report and hit submit when there are 0 elements in the list.

**What is the expected behavior?**
The user should be able to open the precision evaluation report and get a message that there are no positive predictions it's not possible to evaluate the model

**Environment:**
 - OS: MacOS
 - Web browser: Chrome
 - Python version: 3.9
 - Label Sleuth version (as it appears on the bottom left of the UI): 0.11.1

**Suggested solution (if any):**

**Comment by martinscooper** [comment]
Adressed in https://github.com/label-sleuth/label-sleuth/pull/519.
