### ISSUE TITLE
Error when searching for a single parenthesis in the search box

### ISSUE THREAD

**Issue by alonh** [label-sleuth/label-sleuth#570]
**What is the current behavior?**
When searching for `(` in the search panel, the system raises an error:
```Something went wrong. Please ask your system administrator to share the logs by creating an issue on Github or sending a message via Slack```
 
**What is the expected behavior?**
All the texts containing a single parenthesis should appear in the results results on the right panel

**Steps to reproduce the problem:**

1.  Open a workspace
2. Search for `(` in the search panel

**Environment:**
 - OS: MaxOS
 - Web browser: Chrome
 - Python version: 3.9
 - Label Sleuth version (as it appears on the bottom left of the UI): 0.14

**Suggested solution (if any):**

**Comment by martinscooper** [comment]
Resolved by #572.
