### ISSUE TITLE
Request to create Multi Class Classification feature

### ISSUE THREAD

**Issue by sapurtcomputer30** [label-sleuth/label-sleuth#585]
The program is very simple. I am currently developing an intelligent system and need to create a variety of multi-class models to classify my data. But this feature does not exist

This feature can be available as a feature with higher priority than other features

**Comment by alonh** [comment]
We are currently working on multiclass support.

**Comment by arielge** [comment]
@sapurtcomputer30 the latest version (0.18) includes support for multiclass classification. This is a beta feature and we welcome your feedback!
