### ISSUE TITLE
Quoted and escpaed quotes cause dataset uploads to fail

### ISSUE THREAD

**Issue by Ryan1729** [label-sleuth/label-sleuth#590]
**What is the current behavior?**
CSVs containing quoted text entries that have only one quote and end in a quote fail to upload.

Minimal example:
```csv
text
"\""
```
Example with document_id
```
text,document_id
"\"",whatever_name
```

**What is the expected behavior?**
The document should upload successfully and be added to the dataset, including the escaped quote.

**Steps to reproduce the problem:**

1. Upload the a CSV like the following:
```csv
text,document_id
"\"blah blah",whatever_name3
"blah\"",whatever_name3
```
2. Note the error popup and that the data was not added to the dataset.

**Environment:**
 - OS: Ubuntu 22.04
 - Web browser: Firefox 115
 - Python version:  Python 3.9.18
 - Label Sleuth version (as it appears on the bottom left of the UI): Version: 0.17.2

**Comment by arielge** [comment]
Thanks @Ryan1729! We will look into this

**Comment by arielge** [comment]
Fixed (https://github.com/label-sleuth/label-sleuth/commit/5c96cc78c0541517f8c3f111b5fde5a6176bc185)
